
export const ROUTES = {
    LOGIN: 'LOGIN',
    CUSTOMER_HOME: 'CUSTOMER_HOME',
    SEARCH_PAGE: 'SEARCH_PAGE',
    BOOKING_VIEW: 'BOOKING_VIEW',
    RETAILER_DASHBOARD: 'RETAILER_DASHBOARD',
    CUSTOMER_BOOKING: 'CUSTOMER_BOOKING',
    RETAILER_HOME: 'RETAILER_HOME',
    RETAILER_REQUESTS: 'RETAILER_REQUESTS',
    PENDING_REQUESTS: 'PENDING_REQUESTS',
    VIEW_REQUESTS: 'VIEW_REQUESTS',
    CUSTOMER_BOOKING_DASHBOARD: 'CUSTOMER_BOOKING_DASHBOARD',
    CUSTOMER_BOOKING_VIEW: 'CUSTOMER_BOOKING_VIEW',
    RETAILER_VIEW_BOOKINGS: 'RETAILER_VIEW_BOOKINGS'
}

export const PAGE_TYPE = {
    RETAILER_DASHBOARD: ROUTES.RETAILER_DASHBOARD,
    CUSTOMER_BOOKING_DASHBOARD: ROUTES.CUSTOMER_BOOKING_DASHBOARD,
    RETAILER_VIEW_BOOKINGS: ROUTES.RETAILER_VIEW_BOOKINGS,
    PENDING_REQUESTS: ROUTES.PENDING_REQUESTS,
    CUSTOMER_BOOKING: ROUTES.CUSTOMER_BOOKING,
    CUSTOMER_BOOKING_VIEW: ROUTES.CUSTOMER_BOOKING_VIEW,
    PENDING_REQUESTS_VIEW: 'PENDING_REQUESTS_VIEW',
    RETAILER_BOOKING_VIEW: 'RETAILER_BOOKING_VIEW'
}

export const API_TYPE = {
    GET: 'GET',
    POST: 'POST',
    PUT: 'PUT',
    DELETE: 'DELETE',
}

export const USER_TYPE = {
    CUSTOMER: 'CUSTOMER',
    RETAILER: 'RETAILER'
}

export const REQUEST_STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED'
}

export const DATE_TYPE = {
    DD_MM_YYYY: 'dd-mm-yyyy'
}